board = [" "," "," "," "," "," "," "," "," "]

puts "   A     B     C"
puts "      |     |     "
puts "1  #{board[0]}  |  #{board[1]}  |  #{board[2]}  "
puts " _____|_____|_____"
puts "      |     |     "
puts "2  #{board[3]}  |  #{board[4]}  |  #{board[5]}  "
puts " _____|_____|_____"
puts "      |     |     "
puts "3  #{board[6]}  |  #{board[7]}  |  #{board[8]}  "
puts "      |     |     "

puts "Which case do you choose ?"
choice = gets.chomp
case choice
when "A1"
  board[0] = "X"
when "A2"
  board[1] = "X"
when "A3"
  board[2] = "X"
when "B1"
  board[3] = "X"
when "B2"
  board[4] = "X"
when "B3"
  board[5] = "X"
when "C1"
  board[6] = "X"
when "C2"
  board[7] = "X"
when "C3"
  board[8] = "X"
else
  puts "Wrong answer, choose a correct case"
end

puts "   A     B     C"
puts "      |     |     "
puts "1  #{board[0]}  |  #{board[1]}  |  #{board[2]}  "
puts " _____|_____|_____"
puts "      |     |     "
puts "2  #{board[3]}  |  #{board[4]}  |  #{board[5]}  "
puts " _____|_____|_____"
puts "      |     |     "
puts "3  #{board[6]}  |  #{board[7]}  |  #{board[8]}  "
puts "      |     |     "
